# Basic
title: 北哥传奇
subtitle: "人至践，则无敌"
welcome_message: 欢迎进入北哥地盘
description: 嗨，我是饶君波 ，一名来自中国的 iOS 开发者。现居北京，就职于 “作业盒子”。正在修行，探求创意之源。
creator: <a href="https://raojunbo.github.io/</a>

#博客地址
url: "https://raojunbo.github.io/"

permalink: /:year/:month/:title/

# Format
highlighter: rouge

# supported colors: blue, green, purple, red, orange or slate. If you need clear, leave it empty.
cover_color: blue

blog_button:
    title: 博客
    description: 访问博客

nav:
    - {title: 简历, description: 我的简历, url: 'https://raojunbo.github.io/'}
    - {title: 关于, description: 了解更多关于我, url: 'https://raojunbo.github.io/'}
    - {title: 订阅, description: 邮件订阅本站, url: '//store.objccn.io/subscribe'}

# Pagination
plugins: [jekyll-paginate]
paginate: 10
paginate_path: "page/:num/"

# Comment
#这里是评论。我暂时就这个吧
comment:
    disqus: 
    # duoshuo:
# Social
social:
    weibo: 
    github: raojunbo
    twitter: 
    gplus: 
    mail: 1192653008@qq.com

# Google Analytics
#google分析
ga:
    id: 
    host: 
